name: Deploy Frontend # 自动部署的名称

on:
  push:
    tags: # 当我们提交代码为tag 是以'v'开头的时候才会触发自动部署到服务端 如 git push tag v0.1.0
      - 'v*'

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest # 运行环境，告诉它运行在什么环境
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '16.15.2'

    - name: Install dependencies
      run: npm install

    - name: Build frontend
      run: npm run build

    - name: Rename dist directory
      run: mv dist vue-project

    - name: Upload dist folder to server
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        source: vue-project
        target: /hccloud/appserver/examine-tomcat-8096/webapps

